#:include kv/preloginscreen.kv
#:include kv/loginscreen.kv
#:include kv/homescreen.kv
#:import FadeTransition kivy.uix.screenmanager.FadeTransition

GridLayout:
	cols: 1
	ScreenManager:
		transition: FadeTransition()
		id: screen_manager
		PreLoginScreen:
			name: "prelogin_screen"
			id:    prelogin_screen
		LoginScreen:
			name: "login_screen"
			id:    login_screen
	    HomeScreen:
			name: "home_screen"
			id:    home_screen
		
		
